<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mpat</string>
		<string>mscr</string>
		<string>bpat</string>
		<string>bscr</string>
	</array>
	<key>name</key>
	<string>Star Rod Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\/\%</string>
			<key>end</key>
			<string>\%\/</string>
			<key>name</key>
			<string>comment.block.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%[^\n]*</string>
			<key>name</key>
			<string>comment.line.percentage.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(If|Else|EndIf|Thread|EndThread|ChildThread|EndChildThread|Loop|EndLoop|Switch|SwitchConst|Case|CaseOR|CaseAND|EndCaseGroup|EndSwitch|PADDING|to)\b</string>
			<key>name</key>
			<string>keyword.control.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#[A-Za-z:_]+</string>
			<key>name</key>
			<string>storage.type.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[A-Za-z_0-9]+</string>
			<key>name</key>
			<string>entity.name.function.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.[A-Za-z_0-9]+:[A-Za-z_0-9]+</string>
			<key>name</key>
			<string>support.constant.language.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.[A-Za-z_0-9]+</string>
			<key>name</key>
			<string>support.constant.language.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(True|False)</string>
			<key>name</key>
			<string>constant.langauge.boolean.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:\d*\.)?\d+\b</string>
			<key>name</key>
			<string>constant.numeric.float.mscr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*[A-Za-z0-9]+</string>
			<key>name</key>
			<string>variable.parameter.function.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-F0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Call|SetPriority|SetTimescale|SetGroup|Bind|BindLock|Unbind|Kill|Jump|SuspendAll|ResumeAll|SuspendOthers|ResumeOthers|Suspend|Set|Add|Sub|Resume DoesScriptExist|Exec|ExecWait|Wait|WaitSeconds|Jump|Return|End|Exec)\b</string>
			<key>name</key>
			<string>storage.type.mscr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@|==|&gt;|&gt;=|&lt;=|&lt;|\.|\(|\))</string>
			<key>name</key>
			<string>keyword.operator.mscr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.mscr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.mscr</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expression.complex.mscr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9]+</string>
					<key>name</key>
					<string>variable.parameter.function.mscr</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.interpolated.mscr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.interpolated.mscr</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.string.style.mscr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9]+</string>
					<key>name</key>
					<string>string.interpolated.mscr</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mscr</string>
	<key>uuid</key>
	<string>8bd70c81-a94c-47a5-971d-433f5e7a714d</string>
</dict>
</plist>
